-- Active: 1696502791777@@127.0.0.1@3306@accounts
CREATE TABLE grades(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    subject VARCHAR(255),
    date DATE,
    grade FLOAT
) COMMENT '';